spring.datasource.url=jdbc:postgresql://localhost:5432/gateway_db
spring.datasource.username=postgres
spring.datasource.password=Keven#123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do Retry
resilience4j.retry.instances.paymentRetry.max-attempts=3
resilience4j.retry.instances.paymentRetry.wait-duration=2s

# Configuração do Circuit Breaker
resilience4j.circuitbreaker.instances.paymentCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.paymentCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentCB.wait-duration-in-open-state=10s

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer